version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-apache-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v4-php-vendor-{{ checksum "composer.lock" }}
            - v4-php-vendor-
      - run: composer install
      - save_cache:
          key: v4-php-vendor-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: vendor/bin/phpunit
      - run: composer validate --strict
      - run: vendor/bin/parallel-lint src tests

  security-check:
    docker:
      - image: circleci/php:7.1-apache-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-php-vendor-{{ checksum "composer.lock" }}
            - v2-php-vendor-
      - run: composer install
      - save_cache:
          key: v2-php-vendor-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - run: vendor/bin/security-checker security:check

  build-npm:
    docker:
      - image: circleci/node:9

    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-node-vendor-{{ checksum "package-lock.json" }}
            - v3-node-vendor-
      - run: npm install
      - save_cache:
          key: v3-node-vendor-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run scss


workflows:
  version: 2
  commit:
    jobs:
      - build
      - build-npm
      - security-check


  security-check:
    triggers:
      - schedule:
          cron: "35 12 * * *"
          filters:
            branches:
              only: master
    jobs:
      - security-check
