version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-apache-stretch-browsers

    steps:
      - checkout
      - run: mkdir ~/outputs
      - run: echo 'Some output' > ~/outputs/message.log
#      - run: composer validate composer.json
      - restore_cache:
          keys:
            - v2-php-vendor-{{ checksum "composer.lock" }}
            - v2-php-vendor-
      - run: composer install
      - save_cache:
          key: v2-php-vendor-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: mkdir ~/reports
      - run: vendor/bin/phpunit --log-junit ~/reports/phpunit.xml
      - store-test-results:
          path: ~/reports
      - store-artifacts:
          path: ~/outputs


  security-check:
    docker:
      - image: circleci/php:7.1-apache-stretch-browsers

    steps:
        - checkout
        - restore_cache:
          keys:
            - v3-php-vendor-{{ checksum "composer.lock" }}
            - v3php-vendor-
      - run: composer install
      - save_cache:
          key: v3-php-vendor-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: vendor/bin/security-checker security:check



  css-generate:
    docker:
      - image: circleci/node:9

    steps:
        - checkout
        - restore_cache:
            keys:
              - v1-npm-modules-{{ checksum "package.json" }}
              - v1-npm-modules-
        - run: composer install
        - save_cache:
            key: v1-npm-modules-{{ checksum "package.json" }}
            paths:
              - node_modules



workflows:
  version: 2
  commit:
    jobs:
      - build
      - security-check
      - css-generate

  security-check:
    triggers:
      - schedule:
          cron: "35 12 * * *"
          filters:
            branches:
              only: master
    jobs:
      - security-check